config/routes.rb
Cs50::Application.routes.draw do
 

  get "sessions/new"

  resources :users do
    member do
      get :following
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :turfs do
    member do
      get :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]

  resources :chats, :only => [:create, :destroy, :index]
  resources :posts, :only => [:create, :destroy, :index]
  resources :comments, :only => [:create, :destroy]

  resources :locations, :only => [:create]
  match '/votes' => 'votes#create', :via => :get

  get "pages/about"

  get "pages/map"

  get "pages/home2"

  get "pages/oldabout"

  get "users/new"
  get "users/update"

  match '/view', :to =>'users#show'
  match '/signup', :to =>'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/help', :to => 'pages#help'
  match '/profile', :to => 'users#profile'

  root :to => 'pages#home'

  get "turfs/new"
  match '/create', :to =>'turfs#new'
  match '/destroy', :to => 'turfs#destroy'

  get "pages/home"

  get "pages/contanct"

end

app/models/turf.rb
class Turf < ActiveRecord::Base
  #accessible and settable parameters
  attr_accessible :description, :location, :name, :latitude, :longitude, :address

  #users reverse_relationships to define the followeing-follower relationships based
  #on symmetry within a single table
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  #owns many posts
  has_many :posts, :dependent => :destroy

  #owns many chats
  has_many :chats, :dependent => :destroy

  #validations for presence
  validates :name,  :presence => true,
                    :length   => { :maximum => 255 }

  validates :location,  :presence => true,
                    :length   => { :maximum => 255 }

#  searchable do
#    text :name, :default_boost => 2
#    text :description
#  end

  #uses the geocoding API
  reverse_geocoded_by :latitude, :longitude, :address => :location
  after_validation :reverse_geocode, :if => (:latitude_changed? && :longitude_changed?)

  #defines the search function based on both name and location similarity
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end

end

app/controllers/turfs_controller.rb
class TurfsController < ApplicationController
before_filter do
    :authenticate  
  end
  
  #shows a given turf, based on finding it by the given id
  #also performs the VERY IMPORTANT steps of location and following verification.
  #In this method, we follow a turf if it's in range and not already being followed
  def show
    @turf = Turf.find(params[:id])
    if(!current_user.following?(@turf) && in_range(@turf))
      current_user.follow!(@turf)
    end

    @title = in_range(@turf)
    @posts = @turf.posts
    @post = Post.new if signed_in?

    @chats = @turf.chats
    @chat = Chat.new if signed_in?
  end

  #allows a new turf
  def new
	@title = "Create New Turf"
	@turf = Turf.new
  end
  
  #creates a new turf, and stores the lat long and accuracy based on the current used values
  def create
    @turf = Turf.new(params[:turf])
    @turf.latitude = get_location_latitude
    @turf.longitude = get_location_longitude
    @turf.accuracy = get_location_accuracy
    
    if @turf.save
      # Handle a successful save.
      flash[:success] = "Thanks for creating the turf!"
      redirect_to @turf
    else
      @title = "Create New Turf"
      redirect_to "/users"

      #we should definitely fix this long term - this should be in a partial, but i can't get it to work right there
      initial_error = "Sorry, errors prohibited this turf from being created, including:"
      errors = [initial_error]

      if @turf.errors.any?    
        @turf.errors.full_messages.each do |msg|
          errors << msg
        end
        flash[:error] = errors.join("<br/>   - ").html_safe
      end
    end
  end

  def destroy
    @turf = Turf.find(params[:id])
        
    if current_user.email == "admin@turftalk.us"
      if @turf.destroy
        flash[:success] = "Turf destroyed!" 
        redirect_to("/")     
      else
        flash[:error] = "Sorry, turf not destroyed"
      end
    else
      flash[:error] = "Sorry, you don't have permission to destroy that turf."
    end
  end
  
  #the compliment to the user "following" function, delineating the user-turf relationshiop
  #this shows the users currently in a turf
  def followers
	@turf = Turf.find(params[:id])
    @title = "Followers of " + @turf.name
    @users = @turf.followers
    render 'show_follow'
  end

  




end

app/helpers/turf_helper.rb
module TurfHelper
	#can eventually have helper methods for this class
end

app/views/turfs/_join.html.erb
<%= form_for current_user.memberships.
                          build(:turf_id => @turf.id) do |f| %>
  <div><%= f.hidden_field :turf_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/turfs/_join_form.html.erb
<div id="join_form">
  <% if current_user.ismember?(@user) %>
    <%= render 'leave' %>
  <% else %>
    <%= render 'join' %>
  <% end %>
  </div>

app/views/turfs/_joinview.html.erb
<% Turf.all.each do |turf| %>
  <% if silent_in_range(turf) %> 
    <% if !current_user.following?(turf) %>
      <a class="btn btn-large join-button" href = <%=url_for turf_path(turf)%> >
      <div class="left pull-left" style = "text-align:left">
        <td> <div style = "font-size:110%;"><b><%= turf.name %></b></div></td> </br>
        <td><i> <%= pluralize(turf.followers.count, "member") %> </i></td>


      </div>
      
      <div class = "right pull-right" style = "text-align:right">  
        <%if turf.location.size < 35%>
          <td><%= turf.location %></td> </br>
        <% else %>
          <td><%= turf.location.slice(0,35) + "..." %></td> </br>
        <% end %>
        <td><%= sprintf "%.2f", distance_to(turf)%> meters away</td>
      </div>       
      </a>
      
      <button type="button" class="btn btn-link" data-toggle="collapse" data-target=<%="#turf#{turf.id}"%>>
        Description
      </button>

      <div id=<%="turf#{turf.id}"%> class="collapse"> <%=turf.description%> </div>

      

    <%end %>
  <% end %>
<% end %>

app/views/turfs/_leave.html.erb
<%= form_for current_user.memberships.find_by_turf_id(@user),
             :html => { :method => :delete } do |f| %>
  <div class="actions"><%= f.submit "Leave" %></div>
<% end %>

app/views/turfs/_new.html.erb
<!DOCTYPE html>
<html>
<%= form_for(@turf) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.text_field :name, :placeholder => "Name", :id=>"create-form" %>
  </div>
    <div class="field">
    <%= f.text_field :location, :placeholder => "Location", :id=>"create-form" %>
  </div>
  <div class="field">
    <%= f.text_field :description, :placeholder => "Description (optional)", :id=>"create-form"  %>
  </div>

  <div class="actions">
    <%= f.submit "Create Turf", :class=>"btn btn-large btn-primary submit-button"  %>
  </div>
<% end %>
</html>

app/views/turfs/_returnview.html.erb
<% Turf.all.each do |turf| %>
  <% if silent_in_range(turf) %> 
    <% if current_user.following?(turf) %>
    <div>
      <a class="btn btn-large return-button" href = <%=url_for turf_path(turf)%> >
      <div class="left pull-left" style = "text-align:left">
        <td><b><div style = "font-size:130%;"><b><%= turf.name %></b></div></b></td> </br>
        <td><i> <%= pluralize(turf.followers.count, "member") %> </i></td>

      </div>
      
      <div class = "right pull-right" style = "text-align:right">  
        <%if turf.location.size < 25%>
          <td><%= turf.location %></td> </br>
        <% else %>
          <td><%= turf.location.slice(0,25) + "..." %></td> </br>
        <% end %>
        <td><%= sprintf "%.2f", distance_to(turf)%> meters away</td>

      </div>      
      </a>

      <div style = "display:inline-block;">
      <%= form_for current_user.relationships.find_by_followed_id(turf),
             :html => { :method => :delete } do |f| %>
        <div class="actions" ><%= f.submit "Leave", :class=>"leave-button" %></div>
      <% end %>
      </div>

    </div>

    <%end %>
  <% end %>
<% end %>

app/views/turfs/_search.html.erb
<div style = "display:inline-block;">
  <%= form_tag "/users", :method => :get, :remote => :true do %>
    <p>
      <%= text_field_tag :search, params[:search], :placeholder => "Search here", :class=>"search-field", :style => "font-size:130%; padding-top:15px;"%>
      <%= submit_tag "Search", :name => nil, :class=>"btn search-button", :style => "display:inline-block;font-size:130%;height:42px;" %>
  <% end %>


  <div id = "search-results">
  <%if params[:search] && defined? @results %>
  	<h2>There are <%=@results.count%> results for your seach</h2>
  <%end%>
      	<%if params[:search] && defined? @results %>
            <% @results.each do |turf| %>
              <%if !turf.name.nil? %>
              	 <%=render :partial => "turfs/searchview", :locals=>{:turf => turf}%>
              <% end %>     
    	  	  <% end %>  		
    		<% end %>
  </div>

</div>

app/views/turfs/_searchview.html.erb
<% @results.each do |turf| %>
	<a class="btn btn-large join-button" href = <%=url_for turf_path(turf)%> >
	<div class="left pull-left" style = "text-align:left">
	  <td> <div style = "font-size:110%;"><b><%= turf.name %></b></div></td> </br>
	  <td><i> <%= pluralize(@turf.followers.count, "member") %> </i></td>

	</div>

	<div class = "right pull-right" style = "text-align:right">  
	  <%if turf.location.size < 35%>
	    <td><%= turf.location %></td> </br>
	  <% else %>
	    <td><%= turf.location.slice(0,35) + "..." %></td> </br>
	  <% end %>
	  <td><%= sprintf "%.2f", distance_to(turf)%> meters away</td>
	</div>       
	</a>

	<button type="button" class="btn btn-link" data-toggle="collapse" data-target=<%="#turf#{turf.id}"%>>
	  Description
	</button>

	<div id=<%="turf#{turf.id}"%> class="collapse"> <%=turf.description%> </div>
<% end %>

      

app/views/turfs/_summaryview.html.erb
<a class="btn btn-large join-button" href = <%=url_for turf_path(@turf)%> >
  <div class="left pull-left" style = "text-align:left">
    <td> <div style = "font-size:110%;"><b><%= @turf.name %></b></div></td> </br>
    <td><i> <%= pluralize(@turf.followers.count, "member") %> </i></td>

  </div>

  <div class = "right pull-right" style = "text-align:right">  
    <%if @turf.location.size < 35%>
      <td><%= @turf.location %></td> </br>
    <% else %>
      <td><%= @turf.location.slice(0,35) + "..." %></td> </br>
    <% end %>
    <td><%= sprintf "%.2f", distance_to(@turf)%> meters away</td>
  </div>       
  </a>

  <button type="button" class="btn btn-link" data-toggle="collapse" data-target=<%="#@turf#{@turf.id}"%>>
    Description
  </button>

  <div id=<%="@turf#{@turf.id}"%> class="collapse"> <%=@turf.description%> </div>

app/views/turfs/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@turf),
             :html => { :method => :delete } do |f| %>
  <div class="actions" style = "display:inline-block;margin:0; padding:0;"><%= f.submit "Leave", :class => "btn-large unfollow-button"%></div>
<% end %>

app/views/turfs/index.html.erb
<%= form_tag turfs_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<table summary="Search Results">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>
          <% @results.each do |turf| %>
          Turf name is <%= turf.name %>          
          <br/>

      <% end %>

    </td>
  </tr>
</table>

app/views/turfs/new.html.erb
<!DOCTYPE html>
<html>
<div id = "create-form">
<%= form_for(@turf) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit "Create Turf" %>
  </div>
<% end %>
</div>
</html>

app/views/turfs/show.html.erb
<div id = "current_turf" data-turfid= "<%= @turf.id%>">
  <table width="100%" style = "margin-bottom:50px;">

  <div class = "row">
    <tr align="center">

    <td>
    <div class="span8 hero-unit pull-left" id = "turf-header">
      <h1>Welcome to <strong><%= @turf.name %></strong>.</h1>
      <br/>
      <h2>
      Located in <strong> <%= @turf.location %>.</strong>
      This space is <strong> <%= @turf.description %>.</strong></br></h2>
      <h2 style = "display:inline-block;margin-right:50px;"> <%= pluralize(@turf.followers.count, "member") %> </h2>
      
      <%= render 'follow_form' if signed_in? %>
      
      <% if current_user.email == "admin@turftalk.us"%>              
        <h2 style = "display:inline-block;margin-left:50px;">
          <%= link_to "Delete turf as admin", @turf, :method=>:delete, :confirm=>"Are you sure?", :style => "font-style:italic;" %>
        </h2>
      <% end %>

    </div>
    </td>
    </tr>
  </div>
  </table>

  <div class = "row-fluid centered" style="width:1500px;height:750px;">
    <div class="span8 hero-unit" id = "postunit" style = "max-height:900px;" >
      <div class="row-fluid">
        <div class="span3" style="margin-right:5px;margin-left:5px;">
          <div class = "hero-unit post-form" style = "height:240px">        
              <%= render "users/smallpic", :user => current_user %>
              <a href="/profile"><%=current_user.firstname%> <%=current_user.lastname%></a>
              <% @temp = @post %>
              <%= render 'shared/post_form' %>
          </div>

          <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@turf.latitude},#{@turf.longitude}&zoom=14&size=200x200&sensor=false&markers=color:red%7C#{@turf.latitude},#{@turf.longitude}", :class => "img-polaroid"%>

        </div>
        <div class="span9" id = "postview"  style="margin-right:5px;margin-left:5px;">
          <% @post = @temp %>
          <% if @turf.posts.any? %>
            <h2 style = "text-align:left; margin-top:25px; margin-bottom:5px;"><b><%= @turf.posts.count %> posts</b></h2>
            <div class = "post-container" , style = "overflow:scroll; height:800px">  
              <ol class="posts">
                <%= render @posts %>
              </ol>
            </div>
          <%else %>
            <div class = "post-container">
              <h2><i>No posts Yet</i></h2>
            </div>
          <% end %>

        </div>
      </div>
    </div>
    <div class="span3 hero-unit" id = "chatunit" style = "max-height:560px;">
      <h2 style = "text-align:left; margin-top:25px; margin-bottom:5px; padding-bottom:14px;border-bottom: 1px solid #F5D280;"><b>Chat</b></h2>
      <% @temp = @chat %>
      <% if @turf.chats.any? %>
        <div class = "chat-container" style = "overflow:scroll; height:371px;">
          <ol class="chats">
            <div id = "chats-container">
            <%= render @chats.reverse %>
          </div>
          </ol>
        </div>
      <%else %>
        <div class = "chat-container">
          <h3><i>No Chats Yet</i></h3>
        </div>
      <% end %>

      <div class = "chat-form">
        <% @chat = @temp %>
        <%= render 'shared/chat_form' %>
      </div> 
    </div>
  </div>
</div>

app/views/turfs/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>

      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
      <% end %>
    </td>
  </tr>
</table>