config/routes.rb
Cs50::Application.routes.draw do
 

  get "sessions/new"

  resources :users do
    member do
      get :following
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :turfs do
    member do
      get :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]

  resources :chats, :only => [:create, :destroy, :index]
  resources :posts, :only => [:create, :destroy, :index]
  resources :comments, :only => [:create, :destroy]

  resources :locations, :only => [:create]
  match '/votes' => 'votes#create', :via => :get

  get "pages/about"

  get "pages/map"

  get "pages/home2"

  get "pages/oldabout"

  get "users/new"
  get "users/update"

  match '/view', :to =>'users#show'
  match '/signup', :to =>'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/help', :to => 'pages#help'
  match '/profile', :to => 'users#profile'

  root :to => 'pages#home'

  get "turfs/new"
  match '/create', :to =>'turfs#new'
  match '/destroy', :to => 'turfs#destroy'

  get "pages/home"

  get "pages/contanct"

end

app/models/post.rb
class Post < ActiveRecord::Base
  #sets attributes	
  attr_accessible :content
  
  #a post belongs to both a user as a creator and a turf as a location
  belongs_to :turf
  belongs_to :user

  #owns many comments and votes
  has_many :comments, :dependent => :destroy
  has_many :votes, :dependent => :destroy

#  validates :relationship, :presence => true
  validates :user_id, :presence => true
  validates :turf_id, :presence => true
  validates :content, :presence =>true

  default_scope :order => 'posts.created_at DESC'
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate, :setup
  respond_to :html, :js

  #shows a given post based on its parameters, comments, and new comment field
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new if signed_in?
  end

  #allows a new post based on parameters, given comments for a post, and new comments
  def new
    @post = Post.new(params[:post])
    @comments = @post.comments
    @comment = Comment.new if signed_in?
  end

  #can be used to refresh posts
  def index
    logger.debug("Part 7")
    logger.debug(params[:after])
    @posts = Post.where("turf_id = ? and created_at > ?", params[:turf_id], Time.at(params[:after].to_i + 1))
    @posts1 = Post.where("turf_id = ? and id > ?", params[:turf_id], params[:after])
    respond_with(@posts1)
  end

  #creates and attempts to save a new post based on a user and a turf id value passed in
  #from a turf form
  def create
    @user = current_user
    @turf = Turf.find_by_id(params[:post][:turf_id_value])

    @post = @turf.posts.build(:content => params[:post][:content])
    @post.user = current_user

    if @post.save
      respond_with(@post)
      flash[:success] = "Post created!"      
    else
      flash[:error] = "Post not created :("
    end
  end

  #can be used to destroy a post down the line
  def destroy
    @post = Post.find(params[:id])
    
    @turf = Turf.find_by_id(@post.turf_id)
    
    if @post.user_id == current_user.id || current_user.email == "admin@turftalk.us"
      if @post.destroy
        flash[:success] = "Post destroyed!" 
        redirect_to(@turf)     
      else
        flash[:error] = "Sorry, post not destroyed"
      end
    else
      flash[:error] = "Sorry, you don't have permission to destroy that post."
    end
  end

  protected
    #initializes the current turf and user based on params and current logged in user
    def setup      
      @user = current_user
    end
end

app/views/posts/_post.html.erb
<div class = "a_post" data-time= "<%= post.created_at%>" data-id = "<%= post.id %>">

<div style = "min-height:70px;">
  
  <%-#  post.votes.where(:up => true).count - post.votes.where(:up => false).count  -%>
  <div class = "pull-left" id = "updown" style = "padding-top:0px;">
    <div id = <%="#{post.id}up-votes" %> style = "float:left;"><%=post.votes.where(:up => true).count%> </div>
    <div style = "float:right;">
      <%= link_to image_tag("upvote.png"), votes_path(:vote =>{:post_id => post.id, :up => true}), :method=> :get, :remote => :true%>
    </div>
    </br>
    </br>
    <div id = <%="#{post.id}down-votes"%> style = "float:left;"><%=post.votes.where(:up => false).count%></div> 
    <div style = "float:right;">
      <%= link_to image_tag("downvote.png"), votes_path(:vote =>{:post_id => post.id, :up => false}),:method => :get, :remote => :true %>    
    </div>
  </div>
  <div class="timestamp">
    <%= link_to post.user.firstname, post.user, :style => "font-size: 150%;"%> posted (<%= time_ago_in_words(post.created_at) %> ago): 

      <% if post.user_id == current_user.id%>
        <%= link_to "Delete post", post, :method=>:delete, :confirm=>"Are you sure?", :style => "font-style:italic;" %>
      <% elsif current_user.email == "admin@turftalk.us"%>
        <%= link_to "Delete post as admin", post, :method=>:delete, :confirm=>"Are you sure?", :style => "font-style:italic;" %>
      <% end %>

  </div>
  <div class="content" style="margin-left:23px;font-size: 150%;">
    <div class = "pull-left">
      <%= render "users/thumbpic", :user => post.user %>
    </div>
    <%= auto_link(post.content, :html => {:target => "_blank" }) %>
  </div>

</div>


<div class = "post_ind">
  <div class="accordion" id = <%="post#{post.id}"%> >
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent=<%="#post#{post.id}"%> href="#collapsePost<%=post.id%>" >
        <div id = "comment-count<%=post.id%>">
          <%if post.comments.count == 0%>
            No Comments
          <%else%>
              <%=post.comments.count%> Comments
          <%end%>
        </div>          

        

      </a>
    </div>
    <div id= "collapsePost<%=post.id%>" class = "accordion-body collapse">
      <div class="accordion-inner">
         <% if post.comments.any? %>
            <div class = "comments comments_container" , style = "overflow:scroll; height:210px;"> 
            <ol class="comments">
              <div id = "comments-list<%=post.id%>">
                <%= render post.comments.reverse %>
              </div>
              <% @post = post %>
              <%= render "shared/comment_form" %>
            </ol>
            </div>
          <%else %>      
              <div id = "comments-list<%=post.id%>">
              </div>      
            <% @post = post %>
          <%= render "shared/comment_form" %>
          <% end %> 
          
      </div>
    </div>
  </div>
</div>

</div>

</div>

app/views/posts/create.js.erb
$(".post-container").prepend("<%= escape_javascript(render(@post)) %>");
$("#postview h2").html( '<br>' + $('.post_ind').length + " Posts </br>"  );
$("#post_content").val("");

app/views/posts/index.js.erb
<% unless @posts1.empty? %>
$(".post-container").prepend("<%=escape_javascript(render(@posts1))%>");
$("#postview h2").html('<br>' + $('.post_ind').length+" Posts </br>");
<% end %>