config/routes.rb
Cs50::Application.routes.draw do
 

  get "sessions/new"

  resources :users do
    member do
      get :following
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :turfs do
    member do
      get :followers
    end
  end

  resources :relationships, :only => [:create, :destroy]

  resources :chats, :only => [:create, :destroy, :index]
  resources :posts, :only => [:create, :destroy, :index]
  resources :comments, :only => [:create, :destroy]

  resources :locations, :only => [:create]
  match '/votes' => 'votes#create', :via => :get

  get "pages/about"

  get "pages/map"

  get "pages/home2"

  get "pages/oldabout"

  get "users/new"
  get "users/update"

  match '/view', :to =>'users#show'
  match '/signup', :to =>'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/help', :to => 'pages#help'
  match '/profile', :to => 'users#profile'

  root :to => 'pages#home'

  get "turfs/new"
  match '/create', :to =>'turfs#new'
  match '/destroy', :to => 'turfs#destroy'

  get "pages/home"

  get "pages/contanct"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div style = "color:#FFF;size:150%;">
  	<% if url_for(:only_path => true) == "/"%>
	<% else %>
		Developed by James Ruben, Nithin Tumma, and Neel Patel.   
	<% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<% if signed_in? %>
  <div class="navbar-inner" style = "height:47px;">    
<% else %>
  <div class="navbar-inner" style = "height:47px;">    
<% end %>


    <div class="container-fluid">
      <nav>
        <ul class="nav pull-left">
          <% if signed_in? %>
          <% current_user = @user %>
            

            <li><%= link_to "Home", '/users' %></li>
            <li><%= link_to "Learn More", "/pages/about" %></li>
          <% else %>
          

            <li class="divider-vertical"><%= link_to "Home", root_path %></li>

            <!-- <a class="brand" href= <%=root_path%> style = "margin-top:-17px;"><%= image_tag "logo.png", :size => "240x94" %></a> -->
          
          <% end %>
       </ul>


          <% if signed_in? %>
            <ul class="nav pull-right" style = "divider-vertical: 1px solid;">
            <% $name = "#{@current_user.firstname} #{@current_user.lastname}" %>
            <li class="divider-vertical"><%= link_to $name, profile_path %></li>
            <li class="divider-vertical"><%= link_to "Sign out", signout_path, :method => :delete %></li>
          <%else%>
            <ul class="nav pull-right" style = "divider-vertical: 1px solid;">
            <td  style = "pull-left;"><%= render "sessions/new"%></td>
          <% end %>
       </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurfTalk</title>
    <%= csrf_meta_tag %>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  </head>
  <%if "#{request.protocol}#{request.host_with_port}#{request.fullpath}" == root_url %>
    <body id = "homepagebackground">
  <% else %>
    <body>
  <% end %>
  
    <div class="container-fluid">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
    </div>

<div id="side-tabs">
<a class="support" href="mailto:turftalkco@gmail.com?subject=Feedback
&body=Hey, just wanted to give you some quick thoughts on Turftalk:"></a>
</div>
    

    <div>
      
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>